name: dotnet workflow

on: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    
jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        dotnet-version: ['6.0.400']
        
    steps:
      - uses: actions/checkout@v3
#      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
#        uses: actions/setup-dotnet@v2
#        with:
#          dotnet-version: ${{ matrix.dotnet-version }}
#      - name: Install dependencies
#        run: dotnet restore
#      - name: Build
#        run: dotnet build --configuration Release --no-restore
#      - name: Test
#        run: dotnet test --no-restore --verbosity normal
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v3.1.0
        with:
          email: 'diego.rdfaria@gmail.com'
          api_key: 'e1219e75-e4e0-4001-a2b1-c770eb7ce698'
          app_name: 'harry-potter--api'
          dockerfile_path: './HarryPotterApi'
          process_type: 'web'