name: dotnet workflow

env:
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

on: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    
jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        dotnet-version: ['6.0.400']
        
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
#      - name: Test
#        run: dotnet test --no-restore --verbosity normal
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: lucassarcanjo/heroku-deploy@2.1.17  # use the latest version of the action
        with:
          email: "$HEROKU_EMAIL"
          api_key: "$HEROKU_API_KEY"
          app_name: "$HEROKU_APP_NAME"
          dockerfile_path: "./HarryPotterApi"