name: dotnet workflow

on: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    
jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        dotnet-version: ['6.0.400']
        
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
#      - name: Test
#        run: dotnet test --no-restore --verbosity normal
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v3.1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: './HarryPotterApi/Dockerfile'
          process_type: 'web'